# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\UI\ml.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1824, 1465)
        MainWindow.setIconSize(QtCore.QSize(64, 64))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1824, 38))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dw_left = QtWidgets.QDockWidget(MainWindow)
        self.dw_left.setMinimumSize(QtCore.QSize(572, 57))
        self.dw_left.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dw_left.setObjectName("dw_left")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 620, 561, 241))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 50, 461, 47))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sb_train_ratio = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_train_ratio.setFont(font)
        self.sb_train_ratio.setMaximum(100)
        self.sb_train_ratio.setProperty("value", 75)
        self.sb_train_ratio.setObjectName("sb_train_ratio")
        self.horizontalLayout.addWidget(self.sb_train_ratio)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(11, 141, 136, 39))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(149, 141, 411, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 551, 561))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 50, 289, 481))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_load = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_load.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_load.setFont(font)
        self.pb_load.setObjectName("pb_load")
        self.verticalLayout.addWidget(self.pb_load)
        self.pb_feature_rank = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_feature_rank.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_feature_rank.setFont(font)
        self.pb_feature_rank.setObjectName("pb_feature_rank")
        self.verticalLayout.addWidget(self.pb_feature_rank)
        self.pb_train = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_train.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_train.setFont(font)
        self.pb_train.setObjectName("pb_train")
        self.verticalLayout.addWidget(self.pb_train)
        self.pb_test = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_test.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_test.setFont(font)
        self.pb_test.setObjectName("pb_test")
        self.verticalLayout.addWidget(self.pb_test)
        self.pb_predict = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_predict.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_predict.setFont(font)
        self.pb_predict.setObjectName("pb_predict")
        self.verticalLayout.addWidget(self.pb_predict)
        self.dw_left.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dw_left)
        self.dw_right = QtWidgets.QDockWidget(MainWindow)
        self.dw_right.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dw_right.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.RightDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dw_right.setObjectName("dw_right")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.sw_content = QtWidgets.QStackedWidget(self.dockWidgetContents_2)
        self.sw_content.setGeometry(QtCore.QRect(10, 0, 851, 1281))
        self.sw_content.setStyleSheet("border-color: rgb(255, 0, 0);")
        self.sw_content.setFrameShape(QtWidgets.QFrame.Box)
        self.sw_content.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sw_content.setObjectName("sw_content")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.lb_filename = QtWidgets.QLabel(self.page)
        self.lb_filename.setGeometry(QtCore.QRect(0, 10, 801, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_filename.sizePolicy().hasHeightForWidth())
        self.lb_filename.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_filename.setFont(font)
        self.lb_filename.setObjectName("lb_filename")
        self.layoutWidget2 = QtWidgets.QWidget(self.page)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 50, 781, 411))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.vl_1 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.vl_1.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.vl_1.setContentsMargins(0, 0, 0, 0)
        self.vl_1.setObjectName("vl_1")
        self.view_data = QtWidgets.QTableView(self.layoutWidget2)
        self.view_data.setObjectName("view_data")
        self.vl_1.addWidget(self.view_data)
        self.hl_1 = QtWidgets.QHBoxLayout()
        self.hl_1.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.hl_1.setObjectName("hl_1")
        self.view_feature = QtWidgets.QTableView(self.layoutWidget2)
        self.view_feature.setMaximumSize(QtCore.QSize(300, 16777215))
        self.view_feature.setObjectName("view_feature")
        self.hl_1.addWidget(self.view_feature)
        self.lb_feature_rank = QtWidgets.QLabel(self.layoutWidget2)
        self.lb_feature_rank.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_feature_rank.setText("")
        self.lb_feature_rank.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_feature_rank.setObjectName("lb_feature_rank")
        self.hl_1.addWidget(self.lb_feature_rank)
        self.vl_1.addLayout(self.hl_1)
        self.sw_content.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.layoutWidget3 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 731, 281))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lb_train_tip = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lb_train_tip.setFont(font)
        self.lb_train_tip.setStyleSheet("color: rgb(16, 28, 255);")
        self.lb_train_tip.setText("")
        self.lb_train_tip.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_train_tip.setObjectName("lb_train_tip")
        self.verticalLayout_2.addWidget(self.lb_train_tip)
        self.lb_train = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_train.sizePolicy().hasHeightForWidth())
        self.lb_train.setSizePolicy(sizePolicy)
        self.lb_train.setText("")
        self.lb_train.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_train.setObjectName("lb_train")
        self.verticalLayout_2.addWidget(self.lb_train)
        self.sw_content.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.layoutWidget4 = QtWidgets.QWidget(self.page_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 10, 258, 711))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lb_score = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lb_score.setFont(font)
        self.lb_score.setText("")
        self.lb_score.setObjectName("lb_score")
        self.verticalLayout_3.addWidget(self.lb_score)
        self.lb_deviance = QtWidgets.QLabel(self.layoutWidget4)
        self.lb_deviance.setMinimumSize(QtCore.QSize(0, 0))
        self.lb_deviance.setText("")
        self.lb_deviance.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_deviance.setObjectName("lb_deviance")
        self.verticalLayout_3.addWidget(self.lb_deviance)
        self.view_prediction_res = QtWidgets.QTableView(self.layoutWidget4)
        self.view_prediction_res.setMinimumSize(QtCore.QSize(0, 0))
        self.view_prediction_res.setObjectName("view_prediction_res")
        self.verticalLayout_3.addWidget(self.view_prediction_res)
        self.sw_content.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.view_prediction = QtWidgets.QTableView(self.page_4)
        self.view_prediction.setGeometry(QtCore.QRect(0, 0, 851, 261))
        self.view_prediction.setObjectName("view_prediction")
        self.pb_predict_one = QtWidgets.QPushButton(self.page_4)
        self.pb_predict_one.setGeometry(QtCore.QRect(10, 280, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pb_predict_one.setFont(font)
        self.pb_predict_one.setObjectName("pb_predict_one")
        self.sw_content.addWidget(self.page_4)
        self.dw_right.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dw_right)

        self.retranslateUi(MainWindow)
        self.sw_content.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "House Price Prediction by Machine Learning"))
        self.groupBox.setTitle(_translate("MainWindow", "Setting"))
        self.label.setText(_translate("MainWindow", "Percentage Split"))
        self.label_3.setText(_translate("MainWindow", "%"))
        self.label_2.setText(_translate("MainWindow", "Algorithm"))
        self.comboBox.setItemText(0, _translate("MainWindow", "GradientBoostingRegressor"))
        self.groupBox_2.setTitle(_translate("MainWindow", "SystemModel"))
        self.pb_load.setText(_translate("MainWindow", "Load Data"))
        self.pb_feature_rank.setText(_translate("MainWindow", "Feature Ranking"))
        self.pb_train.setText(_translate("MainWindow", "Build Model"))
        self.pb_test.setText(_translate("MainWindow", "Validate Model"))
        self.pb_predict.setText(_translate("MainWindow", "Price Predication"))
        self.lb_filename.setText(_translate("MainWindow", "Load File :"))
        self.pb_predict_one.setText(_translate("MainWindow", "Predict"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

