# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\UI\ml.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1824, 1209)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1824, 38))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dw_left = QtWidgets.QDockWidget(MainWindow)
        self.dw_left.setMinimumSize(QtCore.QSize(572, 57))
        self.dw_left.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dw_left.setObjectName("dw_left")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 410, 531, 681))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 140, 461, 47))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(12, 50, 461, 47))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sb_train_ratio = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_train_ratio.setFont(font)
        self.sb_train_ratio.setMaximum(100)
        self.sb_train_ratio.setProperty("value", 75)
        self.sb_train_ratio.setObjectName("sb_train_ratio")
        self.horizontalLayout.addWidget(self.sb_train_ratio)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.dockWidgetContents)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 202, 326))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_load = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_load.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_load.setFont(font)
        self.pb_load.setObjectName("pb_load")
        self.verticalLayout.addWidget(self.pb_load)
        self.pb_train = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_train.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_train.setFont(font)
        self.pb_train.setObjectName("pb_train")
        self.verticalLayout.addWidget(self.pb_train)
        self.pb_test = QtWidgets.QPushButton(self.layoutWidget1)
        self.pb_test.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_test.setFont(font)
        self.pb_test.setObjectName("pb_test")
        self.verticalLayout.addWidget(self.pb_test)
        self.dw_left.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dw_left)
        self.dw_right = QtWidgets.QDockWidget(MainWindow)
        self.dw_right.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dw_right.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.RightDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dw_right.setObjectName("dw_right")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.sw_content = QtWidgets.QStackedWidget(self.dockWidgetContents_2)
        self.sw_content.setGeometry(QtCore.QRect(10, 0, 851, 891))
        self.sw_content.setStyleSheet("border-color: rgb(255, 0, 0);")
        self.sw_content.setFrameShape(QtWidgets.QFrame.Box)
        self.sw_content.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sw_content.setObjectName("sw_content")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.lb_features = QtWidgets.QLabel(self.page)
        self.lb_features.setGeometry(QtCore.QRect(10, 70, 811, 701))
        self.lb_features.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_features.setText("")
        self.lb_features.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_features.setObjectName("lb_features")
        self.lb_filename = QtWidgets.QLabel(self.page)
        self.lb_filename.setGeometry(QtCore.QRect(0, 10, 801, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_filename.sizePolicy().hasHeightForWidth())
        self.lb_filename.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lb_filename.setFont(font)
        self.lb_filename.setObjectName("lb_filename")
        self.sw_content.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.lb_gif = QtWidgets.QLabel(self.page_2)
        self.lb_gif.setGeometry(QtCore.QRect(130, 70, 521, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_gif.sizePolicy().hasHeightForWidth())
        self.lb_gif.setSizePolicy(sizePolicy)
        self.lb_gif.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_gif.setObjectName("lb_gif")
        self.sw_content.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(210, 150, 89, 25))
        self.label_5.setObjectName("label_5")
        self.sw_content.addWidget(self.page_3)
        self.dw_right.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dw_right)

        self.retranslateUi(MainWindow)
        self.sw_content.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Setting"))
        self.label_2.setText(_translate("MainWindow", "Algorithm"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Linear Regression"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Logistic Regression"))
        self.label.setText(_translate("MainWindow", "Percentage Split"))
        self.label_3.setText(_translate("MainWindow", "%"))
        self.pb_load.setText(_translate("MainWindow", "Load Data"))
        self.pb_train.setText(_translate("MainWindow", "Train"))
        self.pb_test.setText(_translate("MainWindow", "Test"))
        self.lb_filename.setText(_translate("MainWindow", "Load File :"))
        self.lb_gif.setText(_translate("MainWindow", "page 2"))
        self.label_5.setText(_translate("MainWindow", "page 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

