# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\UI\ml.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1824, 1209)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1824, 38))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dw_left = QtWidgets.QDockWidget(MainWindow)
        self.dw_left.setMinimumSize(QtCore.QSize(572, 57))
        self.dw_left.setObjectName("dw_left")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 410, 531, 681))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 160, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(150, 160, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(11, 61, 331, 47))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_train_size = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_train_size.setFont(font)
        self.le_train_size.setObjectName("le_train_size")
        self.horizontalLayout.addWidget(self.le_train_size)
        self.widget1 = QtWidgets.QWidget(self.dockWidgetContents)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 202, 326))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_load = QtWidgets.QPushButton(self.widget1)
        self.pb_load.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_load.setFont(font)
        self.pb_load.setObjectName("pb_load")
        self.verticalLayout.addWidget(self.pb_load)
        self.pb_train = QtWidgets.QPushButton(self.widget1)
        self.pb_train.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_train.setFont(font)
        self.pb_train.setObjectName("pb_train")
        self.verticalLayout.addWidget(self.pb_train)
        self.pb_test = QtWidgets.QPushButton(self.widget1)
        self.pb_test.setMinimumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_test.setFont(font)
        self.pb_test.setObjectName("pb_test")
        self.verticalLayout.addWidget(self.pb_test)
        self.dw_left.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dw_left)
        self.dw_right = QtWidgets.QDockWidget(MainWindow)
        self.dw_right.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dw_right.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.RightDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dw_right.setObjectName("dw_right")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.lb_img = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.lb_img.setGeometry(QtCore.QRect(190, 20, 891, 951))
        self.lb_img.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_img.setObjectName("lb_img")
        self.dw_right.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dw_right)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Setting"))
        self.label_2.setText(_translate("MainWindow", "Algorithm"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Linear Regression"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Logistic Regression"))
        self.label.setText(_translate("MainWindow", "Training Size"))
        self.le_train_size.setText(_translate("MainWindow", "70%"))
        self.pb_load.setText(_translate("MainWindow", "Load Data"))
        self.pb_train.setText(_translate("MainWindow", "Train"))
        self.pb_test.setText(_translate("MainWindow", "Test"))
        self.lb_img.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

